seed:
    42
genres:
    Action: 0
    Animation: 1
    Comédie: 2
    Comédie dramatique: 3
    Documentaire: 4
    Drame: 5
    Thriller-Policier: 6
image_size:
    [100, 100, 3]
testing_split:
    0.15
validation_split:
    0.15
size_per_genre:
    700
model_name:
    cnn_v1
nb_epochs:
    5
batch_size:
    16